export const RAW_PAGES = [
  {
    "id": "1.0",
    "pageTitle": "Emergency Plumber Canada - 24/7 Burst Pipe and Water Leak Repair",
    "pageSlug": "/emergency-plumber",
    "primaryKeyword": "emergency plumber",
    "secondaryKeywords": "emergency plumber near me, 24 hour plumber, burst pipe repair, plumber emergency, 24/7 emergency plumber",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "4800.0",
    "keywordDifficulty": "0.0",
    "cpc": "450.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "2.0",
    "pageTitle": "Emergency Plumber Near Me - Same-Day Response Across Canada",
    "pageSlug": "/emergency-plumber-near-me",
    "primaryKeyword": "emergency plumber near me",
    "secondaryKeywords": "24 hour plumber near me, 24/7 emergency plumber, emergency plumber service near me, plumber open now",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "3900.0",
    "keywordDifficulty": "0.0",
    "cpc": "250.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "3.0",
    "pageTitle": "24 Hour Plumber Canada - Round-the-Clock Emergency Plumbing",
    "pageSlug": "/24-hour-plumber",
    "primaryKeyword": "24 hour plumber",
    "secondaryKeywords": "24 hour plumber near me, 24/7 plumber, round the clock plumber, after hours plumber",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "900.0",
    "keywordDifficulty": "0.0",
    "cpc": "10.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "4.0",
    "pageTitle": "Emergency Electrician Canada - 24/7 Electrical Repair Service",
    "pageSlug": "/emergency-electrician",
    "primaryKeyword": "emergency electrician",
    "secondaryKeywords": "emergency electrician near me, 24 hour electrician, emergency electrical repair, after hours electrician",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "800.0",
    "keywordDifficulty": "0.0",
    "cpc": "180.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "5.0",
    "pageTitle": "Emergency Property Management Canada - 24/7 Maintenance Response",
    "pageSlug": "/emergency-property-management",
    "primaryKeyword": "emergency property management",
    "secondaryKeywords": "24 hour property management, after hours property management, emergency rental repair, emergency maintenance service",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "10.0",
    "keywordDifficulty": "0.0",
    "cpc": "150.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "6.0",
    "pageTitle": "Emergency Tree Removal Canada - 24/7 Storm Damage Response",
    "pageSlug": "/emergency-tree-removal",
    "primaryKeyword": "emergency tree removal",
    "secondaryKeywords": "emergency tree service, storm damage tree removal, fallen tree removal, 24 hour tree removal, emergency arborist",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "170.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "7.0",
    "pageTitle": "Flood Damage Restoration Canada - Emergency Water Damage Repair",
    "pageSlug": "/flood-damage-restoration",
    "primaryKeyword": "flood damage restoration",
    "secondaryKeywords": "flood restoration, water damage restoration, emergency water damage restoration, basement flood repair",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "600.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "8.0",
    "pageTitle": "Emergency HVAC Repair Canada - 24/7 Furnace and AC Response",
    "pageSlug": "/emergency-hvac-repair",
    "primaryKeyword": "emergency hvac repair",
    "secondaryKeywords": "emergency furnace repair, 24 hour HVAC, emergency AC repair, emergency heating repair, hvac emergency",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "40.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "9.0",
    "pageTitle": "Arborist Canada - Certified Tree Care Services | Call 1-888-689-6881",
    "pageSlug": "/arborist",
    "primaryKeyword": "arborist",
    "secondaryKeywords": "certified arborist, arborist near me, what is an arborist, arborist meaning, arborist report",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "2800.0",
    "keywordDifficulty": "24.0",
    "cpc": "350.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "10.0",
    "pageTitle": "Tree Removal Canada - Professional Tree Cutting Services",
    "pageSlug": "/tree-removal",
    "primaryKeyword": "tree removal",
    "secondaryKeywords": "tree removal service, tree cutting service, tree removal company, tree removal near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "800.0",
    "keywordDifficulty": "25.0",
    "cpc": "190.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "11.0",
    "pageTitle": "Tree Trimming and Pruning Canada - Expert Tree Care",
    "pageSlug": "/tree-trimming",
    "primaryKeyword": "tree trimming",
    "secondaryKeywords": "tree pruning, tree trimming near me, tree pruning near me, tree and shrub pruning, tree trimming services",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "3.0",
    "cpc": "60.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "12.0",
    "pageTitle": "Stump Removal Canada - Stump Grinding Services",
    "pageSlug": "/stump-removal",
    "primaryKeyword": "stump removal",
    "secondaryKeywords": "tree stump removal, stump grinding, stump removal near me, stump grinder service, stump removal cost",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "800.0",
    "keywordDifficulty": "4.0",
    "cpc": "50.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "13.0",
    "pageTitle": "Tree Removal Near Me - Local Tree Service Canada",
    "pageSlug": "/tree-removal-near-me",
    "primaryKeyword": "tree removal near me",
    "secondaryKeywords": "tree service near me, tree cutting services near me, tree removal service near me, local tree removal",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Transactional",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "27.0",
    "cpc": "110.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "14.0",
    "pageTitle": "How Much Does Tree Removal Cost in Canada? 2025 Guide",
    "pageSlug": "/tree-removal-cost",
    "primaryKeyword": "tree removal cost",
    "secondaryKeywords": "how much does tree removal cost, cost to remove a tree, tree cutting cost, stump removal cost, arborist cost",
    "targetArea": "Canada (National)",
    "pageType": "Cost Guide",
    "searchIntent": "Informational",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "7.0",
    "cpc": "80.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "15.0",
    "pageTitle": "Painters Near Me - Local House Painters Canada | 1-888-689-6881",
    "pageSlug": "/painters-near-me",
    "primaryKeyword": "painters near me",
    "secondaryKeywords": "house painters near me, interior painters near me, exterior painters near me, local painters near me, residential painters near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Transactional",
    "volumePerMonth": "1900.0",
    "keywordDifficulty": "1.0",
    "cpc": "250.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "16.0",
    "pageTitle": "Interior Painting Canada - Professional Interior Painters",
    "pageSlug": "/interior-painting",
    "primaryKeyword": "interior painting",
    "secondaryKeywords": "interior painting services, interior house painting, interior painting company, interior house painting services",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "1300.0",
    "keywordDifficulty": "27.0",
    "cpc": "25.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "17.0",
    "pageTitle": "Exterior Painting Canada - Exterior House Painters",
    "pageSlug": "/exterior-painting",
    "primaryKeyword": "exterior painting",
    "secondaryKeywords": "exterior painting services, exterior house painting, exterior home painters near me, exterior house painters near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "1100.0",
    "keywordDifficulty": "0.0",
    "cpc": "25.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "18.0",
    "pageTitle": "House Painting Canada - Residential Painters",
    "pageSlug": "/house-painting",
    "primaryKeyword": "house painting",
    "secondaryKeywords": "house painters, house painting services, residential house painting, home painting service",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "1100.0",
    "keywordDifficulty": "6.0",
    "cpc": "35.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "19.0",
    "pageTitle": "Commercial Painting Canada - Business Painting Services",
    "pageSlug": "/commercial-painting",
    "primaryKeyword": "commercial painting",
    "secondaryKeywords": "commercial painting services, commercial painting company, commercial painting service, commercial painters",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "900.0",
    "keywordDifficulty": "3.0",
    "cpc": "300.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "20.0",
    "pageTitle": "Residential Painting Canada - Home Painters",
    "pageSlug": "/residential-painting",
    "primaryKeyword": "residential painting",
    "secondaryKeywords": "residential painting services, residential painting company, residential painters near me, home painters near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "11.0",
    "cpc": "300.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "21.0",
    "pageTitle": "Painting Contractor Canada - Licensed Painting Professionals",
    "pageSlug": "/painting-contractor",
    "primaryKeyword": "painting contractor",
    "secondaryKeywords": "painting service, painting company, licensed painting contractor, professional painting contractor",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "15.0",
    "cpc": "130.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "22.0",
    "pageTitle": "Hardwood Flooring Canada - Installation and Supply",
    "pageSlug": "/hardwood-flooring",
    "primaryKeyword": "hardwood flooring",
    "secondaryKeywords": "hardwood floor installation, engineered hardwood flooring, solid hardwood flooring, white oak hardwood flooring",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "5000.0",
    "keywordDifficulty": "18.0",
    "cpc": "45.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "23.0",
    "pageTitle": "Laminate Flooring Installation Canada - Professional Install",
    "pageSlug": "/laminate-flooring-installation",
    "primaryKeyword": "laminate flooring",
    "secondaryKeywords": "laminate flooring installation, laminate flooring near me, waterproof laminate flooring, laminate floor installer",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "7200.0",
    "keywordDifficulty": "17.0",
    "cpc": "10.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "24.0",
    "pageTitle": "Engineered Hardwood Flooring Canada - Installation and Supply",
    "pageSlug": "/engineered-hardwood-flooring",
    "primaryKeyword": "engineered hardwood flooring",
    "secondaryKeywords": "engineered hardwood floor installation, engineered wood flooring, engineered hardwood vs solid hardwood",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "2900.0",
    "keywordDifficulty": "2.0",
    "cpc": "35.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "25.0",
    "pageTitle": "Flooring Installation Canada - Professional Floor Installers",
    "pageSlug": "/flooring-installation",
    "primaryKeyword": "flooring installation",
    "secondaryKeywords": "flooring installation near me, floor installation, flooring contractor, flooring installer near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "800.0",
    "keywordDifficulty": "0.0",
    "cpc": "90.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "26.0",
    "pageTitle": "Flooring Installation Near Me - Local Flooring Experts Canada",
    "pageSlug": "/flooring-installation-near-me",
    "primaryKeyword": "flooring installation near me",
    "secondaryKeywords": "hardwood flooring near me, laminate flooring near me, vinyl flooring near me, flooring contractor near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Transactional",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "0.0",
    "cpc": "50.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "27.0",
    "pageTitle": "Vinyl Flooring Installation Canada - LVP and Sheet Vinyl",
    "pageSlug": "/vinyl-flooring-installation",
    "primaryKeyword": "vinyl flooring installation",
    "secondaryKeywords": "vinyl plank flooring installation, luxury vinyl plank flooring, waterproof vinyl flooring, vinyl flooring near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "450.0",
    "keywordDifficulty": "16.0",
    "cpc": "30.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "28.0",
    "pageTitle": "Emergency Plumber Toronto - 24/7 Same-Day Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-toronto",
    "primaryKeyword": "emergency plumber toronto",
    "secondaryKeywords": "toronto emergency plumber, 24 hour plumber toronto, burst pipe toronto, plumbing emergency toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "34.0",
    "cpc": "1200.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "29.0",
    "pageTitle": "Emergency Plumber Kingston Ontario - 24/7 | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-kingston",
    "primaryKeyword": "emergency plumber kingston",
    "secondaryKeywords": "emergency plumber kingston ontario, kingston emergency plumber, 24 hour plumber kingston",
    "targetArea": "Kingston, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "400.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "30.0",
    "pageTitle": "Emergency Plumber Ottawa - 24/7 Plumbing Repairs | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-ottawa",
    "primaryKeyword": "emergency plumber ottawa",
    "secondaryKeywords": "ottawa emergency plumber, 24 hour plumber ottawa, burst pipe ottawa, plumbing emergency ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "700.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "31.0",
    "pageTitle": "Emergency Plumber Mississauga - 24/7 Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-mississauga",
    "primaryKeyword": "emergency plumber mississauga",
    "secondaryKeywords": "mississauga emergency plumber, 24 hour plumber mississauga, plumbing emergency mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "1300.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "32.0",
    "pageTitle": "Emergency Plumber Hamilton - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-hamilton",
    "primaryKeyword": "emergency plumber hamilton",
    "secondaryKeywords": "hamilton emergency plumber, 24 hour plumber hamilton, plumbing emergency hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "33.0",
    "pageTitle": "Emergency Plumber Kitchener - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-kitchener",
    "primaryKeyword": "emergency plumber kitchener",
    "secondaryKeywords": "kitchener emergency plumber, plumbing emergency kitchener, 24 hour plumber kitchener",
    "targetArea": "Kitchener, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "1700.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "34.0",
    "pageTitle": "Emergency Plumber Oshawa - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-oshawa",
    "primaryKeyword": "emergency plumber oshawa",
    "secondaryKeywords": "oshawa emergency plumber, plumbing emergency oshawa, 24 hour plumber oshawa",
    "targetArea": "Oshawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "1500.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "35.0",
    "pageTitle": "Emergency Plumber Burlington - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-burlington",
    "primaryKeyword": "emergency plumber burlington",
    "secondaryKeywords": "burlington emergency plumber, plumbing emergency burlington, 24 hour plumber burlington",
    "targetArea": "Burlington, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "1600.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "36.0",
    "pageTitle": "Emergency Plumber Barrie - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-barrie",
    "primaryKeyword": "emergency plumber barrie",
    "secondaryKeywords": "barrie emergency plumber, plumbing emergency barrie, 24 hour plumber barrie",
    "targetArea": "Barrie, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "1.0",
    "cpc": "1200.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "37.0",
    "pageTitle": "Emergency Plumber Ajax - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-ajax",
    "primaryKeyword": "emergency plumber ajax",
    "secondaryKeywords": "ajax emergency plumber, plumbing emergency ajax, 24 hour plumber ajax",
    "targetArea": "Ajax, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "1100.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "38.0",
    "pageTitle": "Emergency Plumber Markham - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-markham",
    "primaryKeyword": "emergency plumber markham",
    "secondaryKeywords": "markham emergency plumber, plumbing emergency markham, 24 hour plumber markham",
    "targetArea": "Markham, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1500.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "39.0",
    "pageTitle": "Emergency Plumber Brampton - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-brampton",
    "primaryKeyword": "emergency plumber brampton",
    "secondaryKeywords": "brampton emergency plumber, plumbing emergency brampton, 24 hour plumber brampton",
    "targetArea": "Brampton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1300.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "40.0",
    "pageTitle": "Emergency Plumber Oakville - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-oakville",
    "primaryKeyword": "emergency plumber oakville",
    "secondaryKeywords": "oakville emergency plumber, plumbing emergency oakville, 24 hour plumber oakville",
    "targetArea": "Oakville, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "3.0",
    "cpc": "1800.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "41.0",
    "pageTitle": "Emergency Plumber Guelph - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-guelph",
    "primaryKeyword": "emergency plumber guelph",
    "secondaryKeywords": "guelph emergency plumber, plumbing emergency guelph, 24 hour plumber guelph",
    "targetArea": "Guelph, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "900.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "42.0",
    "pageTitle": "Emergency Plumber Windsor - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-windsor",
    "primaryKeyword": "emergency plumber windsor",
    "secondaryKeywords": "windsor emergency plumber, plumbing emergency windsor, 24 hour plumber windsor",
    "targetArea": "Windsor, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "43.0",
    "pageTitle": "Emergency Plumber London Ontario - 24/7 | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-london-ontario",
    "primaryKeyword": "emergency plumber london ontario",
    "secondaryKeywords": "london ontario emergency plumber, plumbing emergency london ontario, 24 hour plumber london ontario",
    "targetArea": "London, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "44.0",
    "pageTitle": "Emergency Plumber Pickering - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-pickering",
    "primaryKeyword": "emergency plumber pickering",
    "secondaryKeywords": "pickering emergency plumber, plumbing emergency pickering, 24 hour plumber pickering",
    "targetArea": "Pickering, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1100.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "45.0",
    "pageTitle": "Emergency Plumber Vaughan - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-vaughan",
    "primaryKeyword": "emergency plumber vaughan",
    "secondaryKeywords": "vaughan emergency plumber, plumbing emergency vaughan, 24 hour plumber vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "0.0",
    "cpc": "1500.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "46.0",
    "pageTitle": "Emergency Plumber Whitby - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-whitby",
    "primaryKeyword": "emergency plumber whitby",
    "secondaryKeywords": "whitby emergency plumber, plumbing emergency whitby, 24 hour plumber whitby",
    "targetArea": "Whitby, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1000.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "47.0",
    "pageTitle": "Emergency Plumber Sudbury - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-sudbury",
    "primaryKeyword": "emergency plumber sudbury",
    "secondaryKeywords": "sudbury emergency plumber, plumbing emergency sudbury, 24 hour plumber sudbury",
    "targetArea": "Sudbury, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "48.0",
    "pageTitle": "Painters Toronto - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-toronto",
    "primaryKeyword": "painters toronto",
    "secondaryKeywords": "toronto painters, home painters toronto, house painters toronto, best painters toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "19.0",
    "cpc": "300.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "49.0",
    "pageTitle": "Painters Ottawa - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-ottawa",
    "primaryKeyword": "painters ottawa",
    "secondaryKeywords": "ottawa painters, ottawa house painters, interior painters ottawa, exterior painters ottawa, professional painters ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "500.0",
    "keywordDifficulty": "31.0",
    "cpc": "600.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "50.0",
    "pageTitle": "Painters London Ontario - House and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-london-ontario",
    "primaryKeyword": "painters london ontario",
    "secondaryKeywords": "london ontario painters, house painters london ontario, painting contractor london ontario",
    "targetArea": "London, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "400.0",
    "keywordDifficulty": "15.0",
    "cpc": "350.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "51.0",
    "pageTitle": "Painters Mississauga - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-mississauga",
    "primaryKeyword": "painters mississauga",
    "secondaryKeywords": "mississauga painters, house painters mississauga, painting company mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "52.0",
    "pageTitle": "Painters Hamilton - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-hamilton",
    "primaryKeyword": "painters hamilton",
    "secondaryKeywords": "hamilton painters, house painters hamilton, painting contractor hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "12.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "53.0",
    "pageTitle": "Painters Barrie - Residential and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-barrie",
    "primaryKeyword": "painters barrie",
    "secondaryKeywords": "barrie painters, house painters barrie, home painters barrie, painting company barrie",
    "targetArea": "Barrie, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "12.0",
    "cpc": "450.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "54.0",
    "pageTitle": "Painters Newmarket - House Painters | 1-888-689-6881",
    "pageSlug": "/painters-newmarket",
    "primaryKeyword": "painters newmarket",
    "secondaryKeywords": "newmarket painters, house painters newmarket, painting newmarket",
    "targetArea": "Newmarket, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "8.0",
    "cpc": "450.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "55.0",
    "pageTitle": "Painters Oshawa - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-oshawa",
    "primaryKeyword": "painters oshawa",
    "secondaryKeywords": "oshawa painters, house painters oshawa, painting company oshawa",
    "targetArea": "Oshawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "500.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "56.0",
    "pageTitle": "Painters Brampton - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-brampton",
    "primaryKeyword": "painters brampton",
    "secondaryKeywords": "brampton painters, house painters brampton, painting contractor brampton",
    "targetArea": "Brampton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "57.0",
    "pageTitle": "Painters Oakville - Residential and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-oakville",
    "primaryKeyword": "painters oakville",
    "secondaryKeywords": "oakville painters, house painters oakville, painting company oakville",
    "targetArea": "Oakville, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "2.0",
    "cpc": "350.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "58.0",
    "pageTitle": "Painters Vaughan - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-vaughan",
    "primaryKeyword": "painters vaughan",
    "secondaryKeywords": "vaughan painters, house painters vaughan, painting contractor vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "10.0",
    "cpc": "500.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "59.0",
    "pageTitle": "Painters Ajax - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-ajax",
    "primaryKeyword": "painters ajax",
    "secondaryKeywords": "ajax painters, house painters ajax, painting company ajax",
    "targetArea": "Ajax, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "350.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "60.0",
    "pageTitle": "Painters Pickering - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-pickering",
    "primaryKeyword": "painters pickering",
    "secondaryKeywords": "pickering painters, house painters pickering, painting contractor pickering",
    "targetArea": "Pickering, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "61.0",
    "pageTitle": "Painters Whitby - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-whitby",
    "primaryKeyword": "painters whitby",
    "secondaryKeywords": "whitby painters, house painters whitby, painting company whitby",
    "targetArea": "Whitby, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "450.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "62.0",
    "pageTitle": "Painters Kitchener - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-kitchener",
    "primaryKeyword": "painters kitchener",
    "secondaryKeywords": "kitchener painters, house painters kitchener, painting company kitchener",
    "targetArea": "Kitchener, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "13.0",
    "cpc": "500.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "63.0",
    "pageTitle": "Painters Guelph - Residential and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-guelph",
    "primaryKeyword": "painters guelph",
    "secondaryKeywords": "guelph painters, house painters guelph, painting contractor guelph",
    "targetArea": "Guelph, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "7.0",
    "cpc": "400.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "64.0",
    "pageTitle": "Painters Niagara Falls - House Painters | 1-888-689-6881",
    "pageSlug": "/painters-niagara-falls",
    "primaryKeyword": "painters niagara falls",
    "secondaryKeywords": "niagara falls painters, house painters niagara falls, painting contractor niagara",
    "targetArea": "Niagara Falls, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "6.0",
    "cpc": "300.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "65.0",
    "pageTitle": "Painters Richmond Hill - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-richmond-hill",
    "primaryKeyword": "painters richmond hill",
    "secondaryKeywords": "richmond hill painters, house painters richmond hill, painting company richmond hill",
    "targetArea": "Richmond Hill, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "450.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "66.0",
    "pageTitle": "Painters Markham - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-markham",
    "primaryKeyword": "painters markham",
    "secondaryKeywords": "markham painters, house painters markham, painting contractor markham",
    "targetArea": "Markham, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "67.0",
    "pageTitle": "Painters Burlington - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-burlington",
    "primaryKeyword": "painters burlington",
    "secondaryKeywords": "burlington painters, house painters burlington, painting company burlington",
    "targetArea": "Burlington, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "18.0",
    "cpc": "600.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "68.0",
    "pageTitle": "Painters Windsor - Residential and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-windsor",
    "primaryKeyword": "painters windsor",
    "secondaryKeywords": "windsor painters, house painters windsor, painting contractor windsor",
    "targetArea": "Windsor, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "250.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "69.0",
    "pageTitle": "Tree Removal Toronto - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-toronto",
    "primaryKeyword": "tree removal toronto",
    "secondaryKeywords": "toronto tree removal, arborist toronto, tree service toronto, stump removal toronto, tree cutting toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "24.0",
    "cpc": "600.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "70.0",
    "pageTitle": "Tree Removal Ottawa - Certified Tree Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-ottawa",
    "primaryKeyword": "tree removal ottawa",
    "secondaryKeywords": "ottawa tree removal, arborist ottawa, stump removal ottawa, tree trimming ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "28.0",
    "cpc": "400.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "71.0",
    "pageTitle": "Tree Removal Mississauga - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-mississauga",
    "primaryKeyword": "tree removal mississauga",
    "secondaryKeywords": "mississauga tree removal, arborist mississauga, stump removal mississauga, tree trimming mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "8.0",
    "cpc": "250.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "72.0",
    "pageTitle": "Tree Removal London Ontario - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-london-ontario",
    "primaryKeyword": "tree removal london ontario",
    "secondaryKeywords": "london ontario tree removal, arborist london ontario, stump removal london ontario",
    "targetArea": "London, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "17.0",
    "cpc": "250.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "73.0",
    "pageTitle": "Tree Removal Hamilton - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-hamilton",
    "primaryKeyword": "tree removal hamilton",
    "secondaryKeywords": "hamilton tree removal, arborist hamilton, stump removal hamilton, tree cutting hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "22.0",
    "cpc": "200.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "74.0",
    "pageTitle": "Tree Removal Kitchener - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-kitchener",
    "primaryKeyword": "tree removal kitchener",
    "secondaryKeywords": "kitchener tree removal, kitchener waterloo tree removal, arborist kitchener",
    "targetArea": "Kitchener, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "15.0",
    "cpc": "200.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "75.0",
    "pageTitle": "Tree Removal Oakville - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-oakville",
    "primaryKeyword": "tree removal oakville",
    "secondaryKeywords": "oakville tree removal, arborist oakville, stump removal oakville",
    "targetArea": "Oakville, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "0.0",
    "cpc": "500.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "76.0",
    "pageTitle": "Hardwood Flooring Brampton - Installation and Supply | 1-888-689-6881",
    "pageSlug": "/hardwood-flooring-brampton",
    "primaryKeyword": "brampton hardwood flooring",
    "secondaryKeywords": "hardwood flooring brampton, flooring installation brampton, engineered hardwood flooring brampton",
    "targetArea": "Brampton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "12.0",
    "cpc": "100.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "77.0",
    "pageTitle": "Hardwood Flooring Ottawa - Installation and Supply | 1-888-689-6881",
    "pageSlug": "/hardwood-flooring-ottawa",
    "primaryKeyword": "hardwood flooring ottawa",
    "secondaryKeywords": "ottawa hardwood flooring, hardwood flooring installation ottawa, engineered hardwood flooring ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "9.0",
    "cpc": "90.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "78.0",
    "pageTitle": "Hardwood Flooring Mississauga - Installation | 1-888-689-6881",
    "pageSlug": "/hardwood-flooring-mississauga",
    "primaryKeyword": "hardwood flooring mississauga",
    "secondaryKeywords": "mississauga hardwood flooring, flooring installation mississauga, hardwood flooring installer mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "12.0",
    "cpc": "100.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "79.0",
    "pageTitle": "Flooring Installation Toronto - Hardwood, Vinyl and Laminate | 1-888-689-6881",
    "pageSlug": "/flooring-installation-toronto",
    "primaryKeyword": "flooring installation toronto",
    "secondaryKeywords": "hardwood flooring toronto, vinyl flooring installation toronto, laminate flooring installation toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "9.0",
    "cpc": "350.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "80.0",
    "pageTitle": "Flooring Installation Kitchener - Hardwood and Vinyl | 1-888-689-6881",
    "pageSlug": "/flooring-installation-kitchener",
    "primaryKeyword": "flooring installation kitchener",
    "secondaryKeywords": "vinyl flooring installation kitchener, flooring contractor kitchener, tile flooring installation kitchener",
    "targetArea": "Kitchener, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "81.0",
    "pageTitle": "Painters Calgary - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-calgary",
    "primaryKeyword": "painters calgary",
    "secondaryKeywords": "calgary painters, house painters calgary, interior painters calgary, residential painters calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "1200.0",
    "keywordDifficulty": "22.0",
    "cpc": "450.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "82.0",
    "pageTitle": "Interior Painters Calgary - Professional Interior Painting | 1-888-689-6881",
    "pageSlug": "/interior-painters-calgary",
    "primaryKeyword": "interior painters calgary",
    "secondaryKeywords": "calgary interior painters, interior house painters calgary, interior painting calgary, calgary interior painting",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "450.0",
    "keywordDifficulty": "6.0",
    "cpc": "700.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "83.0",
    "pageTitle": "Exterior Painting Calgary - House Painters | 1-888-689-6881",
    "pageSlug": "/exterior-painting-calgary",
    "primaryKeyword": "exterior painting calgary",
    "secondaryKeywords": "calgary exterior painting, exterior painters calgary, house painting calgary, calgary house painters",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "450.0",
    "keywordDifficulty": "13.0",
    "cpc": "450.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "84.0",
    "pageTitle": "House Painting Calgary - Residential Painters | 1-888-689-6881",
    "pageSlug": "/house-painting-calgary",
    "primaryKeyword": "house painting calgary",
    "secondaryKeywords": "calgary house painting, house painters calgary, residential painting calgary, calgary residential painters",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "6.0",
    "cpc": "500.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "85.0",
    "pageTitle": "Commercial Painters Calgary - Business Painting | 1-888-689-6881",
    "pageSlug": "/commercial-painters-calgary",
    "primaryKeyword": "commercial painters calgary",
    "secondaryKeywords": "calgary commercial painters, commercial painting calgary, painting company calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "28.0",
    "cpc": "1200.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "86.0",
    "pageTitle": "Tree Removal Calgary - Certified Tree Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-calgary",
    "primaryKeyword": "tree removal calgary",
    "secondaryKeywords": "calgary tree removal, arborist calgary, tree trimming calgary, stump removal calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "450.0",
    "keywordDifficulty": "42.0",
    "cpc": "250.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "87.0",
    "pageTitle": "Emergency Plumber Calgary - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-calgary",
    "primaryKeyword": "emergency plumber calgary",
    "secondaryKeywords": "calgary emergency plumber, 24 hour plumber calgary, plumbing emergency calgary, burst pipe calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "900.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "88.0",
    "pageTitle": "Flooring Installation Calgary - Hardwood and Vinyl | 1-888-689-6881",
    "pageSlug": "/flooring-installation-calgary",
    "primaryKeyword": "flooring installation calgary",
    "secondaryKeywords": "hardwood flooring calgary, flooring contractor calgary, laminate flooring calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "200.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "89.0",
    "pageTitle": "Painters Airdrie - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-airdrie",
    "primaryKeyword": "painters airdrie",
    "secondaryKeywords": "airdrie painters, house painters airdrie, painting company airdrie",
    "targetArea": "Airdrie, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "450.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "90.0",
    "pageTitle": "Painters Edmonton - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-edmonton",
    "primaryKeyword": "painters edmonton",
    "secondaryKeywords": "edmonton painters, house painters edmonton, exterior painters edmonton, interior painters edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "500.0",
    "keywordDifficulty": "15.0",
    "cpc": "350.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "91.0",
    "pageTitle": "Tree Removal Edmonton - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-edmonton",
    "primaryKeyword": "tree removal edmonton",
    "secondaryKeywords": "edmonton tree removal, arborist edmonton, tree trimming edmonton, stump removal edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "42.0",
    "cpc": "250.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "92.0",
    "pageTitle": "Emergency Plumber Edmonton - 24/7 Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-edmonton",
    "primaryKeyword": "emergency plumber edmonton",
    "secondaryKeywords": "edmonton emergency plumber, 24 hour plumber edmonton, plumbing emergency edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "93.0",
    "pageTitle": "Painters Lethbridge - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-lethbridge",
    "primaryKeyword": "painters lethbridge",
    "secondaryKeywords": "lethbridge painters, house painters lethbridge, painting contractor lethbridge",
    "targetArea": "Lethbridge, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "5.0",
    "cpc": "150.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "94.0",
    "pageTitle": "Painters Red Deer - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-red-deer",
    "primaryKeyword": "painters red deer",
    "secondaryKeywords": "red deer painters, house painters red deer, painting company red deer",
    "targetArea": "Red Deer, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "10.0",
    "cpc": "150.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "95.0",
    "pageTitle": "Painters Medicine Hat - House Painters | 1-888-689-6881",
    "pageSlug": "/painters-medicine-hat",
    "primaryKeyword": "painters medicine hat",
    "secondaryKeywords": "medicine hat painters, house painters medicine hat, painting company medicine hat",
    "targetArea": "Medicine Hat, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "7.0",
    "cpc": "250.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "96.0",
    "pageTitle": "Painters Vancouver - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-vancouver",
    "primaryKeyword": "painters vancouver",
    "secondaryKeywords": "vancouver painters, house painters vancouver, interior painters vancouver, exterior painters vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "27.0",
    "cpc": "450.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "97.0",
    "pageTitle": "Exterior Painting Vancouver - House Painters | 1-888-689-6881",
    "pageSlug": "/exterior-painting-vancouver",
    "primaryKeyword": "exterior painting vancouver",
    "secondaryKeywords": "vancouver exterior painting company, exterior painters vancouver, exterior house painters vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "450.0",
    "keywordDifficulty": "36.0",
    "cpc": "700.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "98.0",
    "pageTitle": "Interior Painting Vancouver - Professional Painters | 1-888-689-6881",
    "pageSlug": "/interior-painting-vancouver",
    "primaryKeyword": "interior painting vancouver",
    "secondaryKeywords": "vancouver interior painting company, interior painters vancouver, vancouver interior painters",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "400.0",
    "keywordDifficulty": "39.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "99.0",
    "pageTitle": "Emergency Plumber Vancouver - 24/7 Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-vancouver",
    "primaryKeyword": "emergency plumber vancouver",
    "secondaryKeywords": "vancouver emergency plumber, 24 hour plumber vancouver, burst pipe vancouver, plumbing emergency vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "6.0",
    "cpc": "1400.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "100.0",
    "pageTitle": "Painters Surrey - Exterior and Interior Painting | 1-888-689-6881",
    "pageSlug": "/painters-surrey",
    "primaryKeyword": "painters surrey",
    "secondaryKeywords": "surrey painters, house painters surrey, exterior painters surrey, interior painters surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "3.0",
    "cpc": "350.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "101.0",
    "pageTitle": "Exterior Painting Surrey - House Painters | 1-888-689-6881",
    "pageSlug": "/exterior-painting-surrey",
    "primaryKeyword": "exterior painting surrey",
    "secondaryKeywords": "surrey exterior painting company, surrey painting contractor, house painters surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "800.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "102.0",
    "pageTitle": "Painters Burnaby - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-burnaby",
    "primaryKeyword": "painters burnaby",
    "secondaryKeywords": "burnaby painters, house painters burnaby, painting company burnaby",
    "targetArea": "Burnaby, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "600.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "103.0",
    "pageTitle": "Emergency Plumber North Vancouver - 24/7 | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-north-vancouver",
    "primaryKeyword": "emergency plumber north vancouver",
    "secondaryKeywords": "north vancouver emergency plumber, 24 hour plumber north vancouver, plumbing emergency north vancouver",
    "targetArea": "North Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "2000.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "104.0",
    "pageTitle": "Emergency Plumber Victoria BC - 24/7 | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-victoria",
    "primaryKeyword": "emergency plumber victoria",
    "secondaryKeywords": "victoria emergency plumber, 24 hour plumber victoria bc, plumbing emergency victoria",
    "targetArea": "Victoria, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "8.0",
    "cpc": "1700.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "105.0",
    "pageTitle": "Painters Victoria BC - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-victoria",
    "primaryKeyword": "painters victoria",
    "secondaryKeywords": "victoria painters, house painters victoria bc, painting company victoria, painters victoria bc",
    "targetArea": "Victoria, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "14.0",
    "cpc": "500.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "106.0",
    "pageTitle": "Painters Kelowna - Exterior and Interior Painting | 1-888-689-6881",
    "pageSlug": "/painters-kelowna",
    "primaryKeyword": "painters kelowna",
    "secondaryKeywords": "kelowna painters, house painters kelowna, interior painters kelowna, exterior painters kelowna",
    "targetArea": "Kelowna, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "8.0",
    "cpc": "500.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "107.0",
    "pageTitle": "Emergency Plumber Langley - 24/7 Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-langley",
    "primaryKeyword": "emergency plumber langley",
    "secondaryKeywords": "langley emergency plumber, 24 hour plumber langley, plumbing emergency langley",
    "targetArea": "Langley, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "1000.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "108.0",
    "pageTitle": "Painters Nanaimo - Residential and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-nanaimo",
    "primaryKeyword": "painters nanaimo",
    "secondaryKeywords": "nanaimo painters, house painters nanaimo, interior painters nanaimo",
    "targetArea": "Nanaimo, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "5.0",
    "cpc": "300.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "109.0",
    "pageTitle": "Emergency Plumber Burnaby - 24/7 Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-burnaby",
    "primaryKeyword": "emergency plumber burnaby",
    "secondaryKeywords": "burnaby emergency plumber, 24 hour plumber burnaby, plumbing emergency burnaby",
    "targetArea": "Burnaby, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "5.0",
    "cpc": "1600.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "110.0",
    "pageTitle": "Emergency Plumber Surrey - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-surrey",
    "primaryKeyword": "emergency plumber surrey",
    "secondaryKeywords": "surrey emergency plumber, 24 hour plumber surrey, plumbing emergency surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "900.0",
    "priority": "🔴 Top Priority",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "111.0",
    "pageTitle": "Emergency Plumber Abbotsford - 24/7 Service | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-abbotsford",
    "primaryKeyword": "emergency plumber abbotsford",
    "secondaryKeywords": "abbotsford emergency plumber, plumbing emergency abbotsford, 24 hour plumber abbotsford",
    "targetArea": "Abbotsford, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "700.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "112.0",
    "pageTitle": "Painters Richmond - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-richmond",
    "primaryKeyword": "painters richmond",
    "secondaryKeywords": "richmond painters, house painters richmond, painting company richmond",
    "targetArea": "Richmond, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "450.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "113.0",
    "pageTitle": "Painters North Vancouver - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-north-vancouver",
    "primaryKeyword": "north vancouver painters",
    "secondaryKeywords": "painters north vancouver, house painters north vancouver, painting company north vancouver",
    "targetArea": "North Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "900.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "114.0",
    "pageTitle": "Painters Coquitlam - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-coquitlam",
    "primaryKeyword": "painters coquitlam",
    "secondaryKeywords": "coquitlam painters, house painters coquitlam, painting company coquitlam",
    "targetArea": "Coquitlam, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "22.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "115.0",
    "pageTitle": "Emergency Plumber Coquitlam - 24/7 | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-coquitlam",
    "primaryKeyword": "emergency plumber coquitlam",
    "secondaryKeywords": "coquitlam emergency plumber, 24 hour plumber coquitlam, plumbing emergency coquitlam",
    "targetArea": "Coquitlam, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "0.0",
    "cpc": "1700.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "116.0",
    "pageTitle": "Painters Langley - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-langley",
    "primaryKeyword": "painters langley",
    "secondaryKeywords": "langley painters, house painters langley, commercial painters langley",
    "targetArea": "Langley, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "12.0",
    "cpc": "450.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "117.0",
    "pageTitle": "Tree Removal Vancouver - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-vancouver",
    "primaryKeyword": "tree removal vancouver",
    "secondaryKeywords": "vancouver tree removal, arborist vancouver, stump removal vancouver, tree cutting vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "3.0",
    "cpc": "190.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "118.0",
    "pageTitle": "Tree Removal Surrey - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-surrey",
    "primaryKeyword": "tree removal surrey",
    "secondaryKeywords": "surrey tree removal, arborist surrey, stump removal surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "6.0",
    "cpc": "200.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "119.0",
    "pageTitle": "Tree Removal North Vancouver - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-north-vancouver",
    "primaryKeyword": "tree removal north vancouver",
    "secondaryKeywords": "north vancouver tree removal, arborist north vancouver, stump removal north vancouver",
    "targetArea": "North Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "19.0",
    "cpc": "250.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "120.0",
    "pageTitle": "Painters Abbotsford - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-abbotsford",
    "primaryKeyword": "painters abbotsford",
    "secondaryKeywords": "abbotsford painters, house painters abbotsford, painting contractor abbotsford",
    "targetArea": "Abbotsford, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "10.0",
    "cpc": "300.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "121.0",
    "pageTitle": "Painters Port Coquitlam - Residential Painting | 1-888-689-6881",
    "pageSlug": "/painters-port-coquitlam",
    "primaryKeyword": "painters port coquitlam",
    "secondaryKeywords": "port coquitlam painters, house painters port coquitlam, painting company port coquitlam",
    "targetArea": "Port Coquitlam, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "21.0",
    "cpc": "450.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "122.0",
    "pageTitle": "Painters Winnipeg - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-winnipeg",
    "primaryKeyword": "painters winnipeg",
    "secondaryKeywords": "winnipeg painters, house painters winnipeg, interior painters winnipeg, exterior painters winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "20.0",
    "cpc": "400.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "123.0",
    "pageTitle": "Tree Removal Winnipeg - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-winnipeg",
    "primaryKeyword": "tree removal winnipeg",
    "secondaryKeywords": "winnipeg tree removal, arborist winnipeg, stump removal winnipeg, tree trimming winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "34.0",
    "cpc": "70.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "124.0",
    "pageTitle": "Emergency Plumber Winnipeg - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-winnipeg",
    "primaryKeyword": "emergency plumber winnipeg",
    "secondaryKeywords": "winnipeg emergency plumber, 24 hour plumber winnipeg, plumbing emergency winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "300.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "125.0",
    "pageTitle": "Painters Saskatoon - Residential and Commercial Painting | 1-888-689-6881",
    "pageSlug": "/painters-saskatoon",
    "primaryKeyword": "painters saskatoon",
    "secondaryKeywords": "saskatoon painters, house painters saskatoon, interior painters saskatoon",
    "targetArea": "Saskatoon, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "9.0",
    "cpc": "150.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "126.0",
    "pageTitle": "Painters Regina - House Painting Services | 1-888-689-6881",
    "pageSlug": "/painters-regina",
    "primaryKeyword": "painters regina",
    "secondaryKeywords": "regina painters, house painters regina, painting company regina, professional painters regina",
    "targetArea": "Regina, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "16.0",
    "cpc": "200.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "127.0",
    "pageTitle": "Tree Removal Saskatoon - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-saskatoon",
    "primaryKeyword": "tree removal saskatoon",
    "secondaryKeywords": "saskatoon tree removal, arborist saskatoon, stump removal saskatoon",
    "targetArea": "Saskatoon, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "24.0",
    "cpc": "100.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "128.0",
    "pageTitle": "Tree Removal Regina - Certified Tree Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-regina",
    "primaryKeyword": "tree removal regina",
    "secondaryKeywords": "regina tree removal, arborist regina, stump removal regina",
    "targetArea": "Regina, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "13.0",
    "cpc": "200.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "129.0",
    "pageTitle": "Painters Halifax - Interior and Exterior Painting | 1-888-689-6881",
    "pageSlug": "/painters-halifax",
    "primaryKeyword": "painters halifax",
    "secondaryKeywords": "halifax painters, house painters halifax, interior painters halifax, exterior painters halifax",
    "targetArea": "Halifax, NS",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "22.0",
    "cpc": "200.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "130.0",
    "pageTitle": "Emergency Plumber Halifax - 24/7 Plumbing | 1-888-689-6881",
    "pageSlug": "/emergency-plumber-halifax",
    "primaryKeyword": "emergency plumber halifax",
    "secondaryKeywords": "halifax emergency plumber, 24 hour plumber halifax, plumbing emergency halifax",
    "targetArea": "Halifax, NS",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "4.0",
    "cpc": "100.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "131.0",
    "pageTitle": "Tree Removal Kelowna - Arborist Services | 1-888-689-6881",
    "pageSlug": "/tree-removal-kelowna",
    "primaryKeyword": "tree removal kelowna",
    "secondaryKeywords": "kelowna tree removal, arborist kelowna, stump removal kelowna",
    "targetArea": "Kelowna, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "33.0",
    "cpc": "200.0",
    "priority": "🟠 High",
    "ctaStrategy": "Call 1-888-689-6881"
  },
  {
    "id": "132.0",
    "pageTitle": "Tree Removal Red Deer - Certified Arborists | 1-888-689-6881",
    "pageSlug": "/tree-removal-red-deer",
    "primaryKeyword": "tree removal red deer",
    "secondaryKeywords": "red deer tree removal, arborist red deer, stump removal red deer",
    "targetArea": "Red Deer, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "80.0",
    "priority": "🟡 Medium",
    "ctaStrategy": "Call 1-888-689-6881"
  }
] as const;
